[build]
  command = "npm run build"
  publish = "dist"
  
[build.environment]
  VITE_API_URL = "https://gospel-chant-et-parole.onrender.com"
  VITE_API_BASE_URL = "https://gospel-chant-et-parole.onrender.com"
  VITE_NODE_ENV = "production"
  VITE_JWT_STORAGE_KEY = "gospel_admin_token"
  VITE_JWT_EXPIRE_TIME = "604800000"
  VITE_LOGIN_REDIRECT_URL = "/dashboard"
  VITE_LOGOUT_REDIRECT_URL = "/login"
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
